### ISSUE TITLE
RGBA Alpha doesn't work properly - bug

### ISSUE THREAD

**Issue by onepersonintheuniverse** [fusionengine-org/fusion#16]
This code inside the loop below: 
```py
main.draw.draw_rect(window, 0, 0, 100, 100, (0x02, 0x8a, 0xf2, 0xff))
main.draw.draw_rect(window, 50, 50, 100, 100, (0x4a, 0xf2, 0x02, 0x7f))
```
Should produce [this](https://github.com/dimkauzh/fusion-engine/assets/67820127/242b5d2e-9b93-4ef1-bb11-a95b4d93cfd7), but instead, the green square is treated as if it is fully opaque (alpha = 255) and produces [this](https://github.com/dimkauzh/fusion-engine/assets/67820127/424c969d-76d9-4d1d-b1c7-310703abe943), which is not correct.

**Comment by dimkauzh** [comment]
Hmm this is weird. I will try to test it, but if I'm sure the api only allows rgba 0-255 that's due SDL2.

**Comment by dimkauzh** [comment]
Hey, so I looked through the sdl2 api, and yes it only supports alpha from 0 to 255, and not hex. Here the api link:
https://wiki.libsdl.org/SDL2/SDL_SetRenderDrawColor
I'm don't think hex would work in this situation, maybe try using RGBA 0-255. Sorry for this weird issue, I will try to look maybe there is something wrong, but I don't think I could do much about it @Techsplosion

**Comment by onepersonintheuniverse** [comment]
> Hey, so I looked through the sdl2 api, and yes it only supports alpha from 0 to 255, and not hex. Here the api link: https://wiki.libsdl.org/SDL2/SDL_SetRenderDrawColor I'm don't think hex would work in this situation, maybe try using RGBA 0-255. Sorry for this weird issue, I will try to look maybe there is something wrong, but I don't think I could do much about it @Techsplosion

Using `0xff` and `0x7f` in Python (and many other programming languages) it converts the hex number into an integer, so therefore using `0x` at the beginning makes it an integer, not a string, and both values are between 0 and 255. For example, if I wrote `print(0x10)`, it would print 16 because 10 in hex is 16. So I'm actually giving integers between 0 and 255, so that is not the problem. I ran this code:
```py
main.draw.draw_rect(window, 0, 0, 100, 100, (2, 138, 242, 255))
main.draw.draw_rect(window, 50, 50, 100, 100, (74, 242, 2, 127))
```
And it gave me the exact same results @dimkauzh

**Comment by dimkauzh** [comment]
Oh that's weird, thanks for explanation, I will test it myself and fix it. Thanks!

**Comment by onepersonintheuniverse** [comment]
> Oh that's weird, thanks for explanation, I will test it myself and fix it. Thanks!

Hey @dimkauzh, any updates on the bug?

**Comment by dimkauzh** [comment]
> 
> > Oh that's weird, thanks for explanation, I will test it myself and fix it. Thanks!
> 
> Hey @dimkauzh, any updates on the bug?
> 

Yes, I found a way to fix it, but it will take time due to its complexity. I think I will commit a fix today, maybe in like 5 hours because I need to do some stuff.

**Comment by dimkauzh** [comment]
> 
> > Oh that's weird, thanks for explanation, I will test it myself and fix it. Thanks!
> 
> Hey @dimkauzh, any updates on the bug?
> 

But also, I found lots of articles how it works, and the code should have worked but it doesn't. I'm actually even thinking I can not fix it because it's a bug of pysdl2, binding to sdl2 for python.

**Comment by dimkauzh** [comment]
@Techsplosion The bug if fixed, i forgot to add a renderer flag, but now it works. To install the latest version, please do this:
### Latest build
if you want to get the latest changes then follow this instruction:
```bash
 git clone https://github.com/dimkauzh/fusion-engine
 cd fusion-engine
 pip install -e .
 ```
