### ISSUE TITLE
Entity images don't work

### ISSUE THREAD

**Issue by onepersonintheuniverse** [fusionengine-org/fusion#17]
The `Entity.image(window, image_path, x, y, width, height)` method is supposed to render an image for the entity, but in the method, instead of the `image` argument using `image_path` in the `open_image` method, it uses `image`, which causes an error when running the `Entity.image` method.

**Comment by dimkauzh** [comment]
Hey, I know it doesn't work, I'm still working on it as hard as possible, but till now don't use the entity system because it's not even ready for 20%

**Comment by onepersonintheuniverse** [comment]
Instead of `drawimage = self.image_fe.open_image(window, image, x, y, width, height)` use `drawimage = self.image_fe.open_image(window, image_path, x, y, width, height)` in `Entity.image`.
