### ISSUE TITLE
Redundant files and debugfiles directories

### ISSUE THREAD

**Issue by zenthm** [fusionengine-org/fusion#19]
The `src/fusionengine/files` and `src/fusionengine/debugfiles` directories are redundant and absurd, the contents of these directories should be placed in the `src/fusionengine` directory.

The `src/fusionengine/debugfiles/fe.png` file can be `src/fusionengine/icon.png`.

**Comment by dimkauzh** [comment]
@zenthm 
Hey, I see what you mean, but I still wanna stick to it due a reason

 - If the user imports fusionengine,  then I want init.py to be the only thing import-able, and if you want to import other files you do that through fusionengine.files.
