### ISSUE TITLE
PR and Issue Templates

### ISSUE THREAD

**Issue by zenthm** [fusionengine-org/fusion#20]
This project should have PR and Issue templates for the following reasons:

- **Consistency**: Templates ensure that all PRs and issues follow a standardized structure and format.
- **Clear Information**: Templates prompt contributors to provide specific details about the PR or issue they are submitting.
- **Guidance for Contributors**: Templates can serve as guidance for contributors who might be new to the project or inexperienced with the submission process.
- **Enhanced Project Management**: By using templates, the project maintains a higher level of organization.

**Comment by dimkauzh** [comment]
Okay sure, will create then (not now i think)

**Comment by dimkauzh** [comment]
Okay, everything is created!

**Comment by zenthm** [comment]
Uh, didn't you add the PR template?

**Comment by zenthm** [comment]
Take a look at [black](https://github.com/psf/black/blob/main/.github/PULL_REQUEST_TEMPLATE.md)'s PR template.

**Comment by dimkauzh** [comment]
> Uh, didn't you add the PR template?

Wait you ment issue template right? I did add those

**Comment by zenthm** [comment]
> > Uh, didn't you add the PR template?
> 
> Wait you ment issue template right? I did add those

There's also a PR template `.github/PULL_REQUEST_TEMPLATE.md`.

**Comment by dimkauzh** [comment]
> > > Uh, didn't you add the PR template?
> > 
> > Wait you ment issue template right? I did add those
> 
> There's also a PR template `.github/PULL_REQUEST_TEMPLATE.md`.

Ooh yeah I forgot about those sorry will add them
