### ISSUE TITLE
implementation of sending text through screen readers.

### ISSUE THREAD

**Issue by Glowing-Radiant** [fusionengine-org/fusion#41]
hi, it'd be great if you could implement pyping text through screen readers, preferably from here.
[](https://github.com/pauliyobo/cytolk)

**Comment by dimkauzh** [comment]
Okay, i will think about it!

**Comment by dimkauzh** [comment]
@pool-prateek Hey, so i wanted to make sure if i understood you correctly: You want me to implement something like text-to-speech functionallyity through screen readers?

**Comment by Glowing-Radiant** [comment]
yes. the reppo I mentioned above supports both windos speach and screen readers.

**Comment by dimkauzh** [comment]
Okay, i will look though the library and think how i could implement it

**Comment by dimkauzh** [comment]
@pool-prateek Is it okay if i use pyttsx3? Cytolk is a bit outdated/doesnt support newest python.

**Comment by Glowing-Radiant** [comment]
I am not sure about that one. you could also look into accessible output 2 as it is still active and even cross platform.

**Comment by Glowing-Radiant** [comment]
the problem with pyttsx3 is that it doesnt support screen readers. and many screen reader users prefer to use their own screen reader configuration over tts engines provided by windos.

**Comment by zenthm** [comment]
This feature is way too advanced and maybe just postpone this.

**Comment by dimkauzh** [comment]
> .

Yeah zenthm is probably right.

**Comment by onepersonintheuniverse** [comment]
I agree, TTSR (text thru screen readers) should probably be postponed as it is a compilcated feature.

**Comment by dimkauzh** [comment]
> I agree, TTSR (text thru screen readers) should probably be postponed as it is a compilcated feature.

Yeah
