### ISSUE TITLE
Need to make it not possible to close window w/o killing process

### ISSUE THREAD

**Issue by onepersonintheuniverse** [fusionengine-org/fusion#47]
This feature is (pretty much) required for my game [Dot](https://github.com/Techsplosion/Dot). The entire game can be skipped via closing the window (which skips to the next level). 

I'd prefer a method -something named like `window.disable_close()`-. It disables the close button like on error popups.

I have considered directly interacting with `window.window` - although I will have to do some research on PyGame.

For example, the feature request would make ![enabled_close](https://github.com/dimkauzh/fusion-engine/assets/67820127/925fb39a-f65c-45b6-b664-3b428a61f7e7) look like ![disabled_close](https://github.com/dimkauzh/fusion-engine/assets/67820127/5862a557-b484-46bf-b69f-c85721326908).

**Comment by nmsderp** [comment]
This has very much been needed

**Comment by zenthm** [comment]
Well, this is maybe impossible to implement since the library depends on pygame which doesn't have this feature and also SDL2 (which pygame depends on) doesn't have this I think.

**Comment by onepersonintheuniverse** [comment]
> Well, this is maybe impossible to implement since the library depends on pygame which doesn't have this feature and also SDL2 (which pygame depends on) doesn't have this I think.

I'm fine with making the close button do nothing. Also, it would be nice to have an enable function as well.

**Comment by dimkauzh** [comment]
> > Well, this is maybe impossible to implement since the library depends on pygame which doesn't have this feature and also SDL2 (which pygame depends on) doesn't have this I think.
> 
> I'm fine with making the close button do nothing. Also, it would be nice to have an enable function as well.

Yes I can do that it's no problem. But gimme time, I can't do it today. Maybe it will come in the next release.

**Comment by onepersonintheuniverse** [comment]
> > > Well, this is maybe impossible to implement since the library depends on pygame which doesn't have this feature and also SDL2 (which pygame depends on) doesn't have this I think.
> > 
> > 
> > I'm fine with making the close button do nothing. Also, it would be nice to have an enable function as well.
> 
> Yes I can do that it's no problem. But gimme time, I can't do it today. Maybe it will come in the next release.

Aight, fine with me.

**Comment by onepersonintheuniverse** [comment]
@dimkauzh Please check out #48.
