### ISSUE TITLE
Textures covered up by transparent textures on top

### ISSUE THREAD

**Issue by onepersonintheuniverse** [fusionengine-org/fusion#49]
The bug is that transparent textures render over other textures, despite being transparent.

You need to create two textures, one transparent, and draw the transparent texture over the non-transparent one by calling the transp. texture draw after the non-transp. texture draw. Non-transp. will *not* render.

The non-transp. texture should render.

I have two screenshots that are important, one showing where no texture is on top of another and another where there is. The texture has solid pixels, but the background is transparent.

[This](https://github.com/dimkauzh/fusion-engine/assets/67820127/ef26f388-229e-4150-9f1d-092d9b2f50e7) is without the overlap.
[This](https://github.com/dimkauzh/fusion-engine/assets/67820127/e3b59e65-bd59-4b71-aef1-147c47b1e7cf) demonstrates the bug. The yellow dot has a transparent background.
[This](https://github.com/dimkauzh/fusion-engine/assets/67820127/0dff65e6-2471-493a-90d1-c8bd7bea5bf1) demonstrates how it should look. I did some image editing in order to achieve the picture.

I see this issue in Windows 11 Moment 4 Update.

I witnessed the issue before, though.

**Comment by dimkauzh** [comment]
Hey, what function do you use for drawing the image?

**Comment by dimkauzh** [comment]
Nevermind i see what your talking about

**Comment by dimkauzh** [comment]
@Techsplosion I fixed it, im gonna release v3.0.8 right now

**Comment by onepersonintheuniverse** [comment]
The fix works, thanks!
Also, what about the GitHub release?

**Comment by dimkauzh** [comment]
> The fix works, thanks!
> Also, what about the GitHub release?

I will do it as fast as possible. It's probably gonna be up in 5 hours
