### ISSUE TITLE
Textures not clearing properly

### ISSUE THREAD

**Issue by onepersonintheuniverse** [fusionengine-org/fusion#50]
The textures do not properly clear, and the previous frame's render can be seen.

Create a program with a moving texture.

The textures should clear.

Expected
![expected](https://github.com/dimkauzh/fusion-engine/assets/67820127/f18ca84a-c238-407d-84de-a4ea2ddf315e)
Reality
![reality](https://github.com/dimkauzh/fusion-engine/assets/67820127/46e854e3-d357-43ad-9460-25f400a2c534)
Windows 11 Moment 4 update, observed in previous OS releases.

**Comment by dimkauzh** [comment]
Yeah i know lmfao.
I'm fixing it now

**Comment by dimkauzh** [comment]
@Techsplosion I fixed it, you should be able to install v4.0.4 in a few minutes. (`pip install --upgrade fusion-engine`)
