### ISSUE TITLE
Ruff implementation

### ISSUE THREAD

**Issue by zenthm** [fusionengine-org/fusion#65]
## Description

The project has a poor CI (Continuous Integration) at the time, and this issue is dedicated for adding a simple CI for linting the project and formatting with [Ruff](https://docs.astral.sh/ruff/). This tool is a new absurdly fast all-in-one tool for linting and formatting, which means we don't need to set up other tools (e.g., isort, black, flake8, etc.)

**Comment by zenthm** [comment]
Assign me for this, I'll also setup the CI

**Comment by dimkauzh** [comment]
> Assign me for this, I'll also setup the CI

Sure, you can work on it lol
